accepted = [
    "MIT",
    "Apache-2.0",
    "Unicode-3.0"
]

targets = [
    "x86_64-pc-windows-msvc",
    "x86_64-apple-darwin",
    "aarch64-apple-darwin",
]

private = { ignore = true }
ignore-build-dependencies = true
ignore-dev-dependencies = true