# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    strategy:
      matrix:
        include:
          - build: Windows (x64)
            os: windows-latest
            target: x86_64-pc-windows-msvc
          - build: MacOS (x64)
            os: macos-13
            target: x86_64-apple-darwin
          - build: macos-arm
            os: macos-latest
            target: aarch64-apple-darwin
        
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4
    - uses: dtolnay/rust-toolchain@master
      with:
        toolchain: stable
        target: ${{ matrix.target }}
    - run: cargo build --target ${{ matrix.target }}
    - run: cargo test --target ${{ matrix.target }}
    - uses: actions/upload-artifact@v4
      with:
        name: build-${{ matrix.target }}
        path: target/${{ matrix.target }}/debug/livetagger*