# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Release

on:
  release:
    types: [published]

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Publish
      run: |
        dotnet publish src -r win-x64
        dotnet publish src -r osx-x64
        dotnet publish src -r osx-arm64
    - name: Zip artifacts
      run: |
        tag=$(git describe --tags --abbrev=0)

        7z a "livetagger-$tag-win-x64.zip" "./src/bin/Release/net8.0/win-x64/publish/*"
        7z a "livetagger-$tag-osx-x64.zip" "./src/bin/Release/net8.0/osx-x64/publish/*"
        7z a "livetagger-$tag-osx-arm64.zip" "./src/bin/Release/net8.0/osx-arm64/publish/*"
    - name: Publish
      uses: softprops/action-gh-release@v2
      with:
        files: "livetagger*"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
