name: Release

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  release:
    name: ${{ matrix.target }}

    permissions:
      contents: write

    strategy:
      matrix:
        include:
          - target: x86_64-pc-windows-msvc
            os: windows-latest
          - target: x86_64-apple-darwin
            os: macos-13
          - target: aarch64-apple-darwin
            os: macos-latest
      
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4
    - uses: dtolnay/rust-toolchain@master
      with:
        toolchain: stable
        target: ${{ matrix.target }}
    - name: Document licenses
      shell: bash
      run: | 
        cargo install --locked cargo-about
        cargo about generate about.hbs -o licenses.html
    - name: Build
      shell: bash
      run: |
        if [ "${{ github.event_name }}" = "release" ]; then
          tag=$(git describe --tags --abbrev=0)
        else
          tag="manual-build"
        fi

        cargo build --release --target ${{ matrix.target }}

        if [ "${{ matrix.os }}" = "windows-latest" ]; then
          bin="./target/${{ matrix.target }}/release/livetagger.exe"
        else
          bin="./target/${{ matrix.target }}/release/livetagger"
        fi

        7z a "livetagger-$tag-${{ matrix.target }}.zip" $bin licenses.html
    - name: Attach artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.target }}
        path: livetagger*
    - name: Publish
      uses: softprops/action-gh-release@v2
      if: github.event_name == 'release'
      with:
        files: "livetagger*"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}